<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Route Permissions
    |--------------------------------------------------------------------------
    | Keys are Laravel route names. Permission slugs are route.{route_name}.
    */
    'routes' => [
        'dashboard' => 'Dashboard',
        'logout' => 'Logout',
        'sales.patient-visits.today-recent' => 'Today recent patient visits API',
        'patient-visits.show' => 'View patient visit',
        'patient-visits.diagnoses.store' => 'Store patient visit diagnosis',
        'patient-visits.diagnoses.edit' => 'Edit patient visit diagnosis form',
        'patient-visits.diagnoses.update' => 'Update patient visit diagnosis',
        'patients.index' => 'List patients',
        'patients.create' => 'Create patient form',
        'patients.store' => 'Store patient',
        'patients.show' => 'View patient profile',
        'patients.edit' => 'Edit patient form',
        'patients.update' => 'Update patient',
        'patients.visit-records.create' => 'Create patient visit record form',
        'patients.visit-records.store' => 'Store patient visit record',
        'patients.visit-records.edit' => 'Edit patient visit record form',
        'patients.visit-records.update' => 'Update patient visit record',
        'finance.income.index' => 'List income entries',
        'finance.income.create' => 'Create income entry form',
        'finance.income.store' => 'Store income entry',
        'finance.income.edit' => 'Edit income entry form',
        'finance.income.update' => 'Update income entry',
        'finance.expenses.index' => 'List expense entries',
        'finance.expenses.create' => 'Create expense entry form',
        'finance.expenses.store' => 'Store expense entry',
        'finance.expenses.edit' => 'Edit expense entry form',
        'finance.expenses.update' => 'Update expense entry',
        'sales.index' => 'Sales history',
        'sales.pos' => 'POS screen',
        'sales.hold' => 'Hold sale',
        'sales.store' => 'Complete sale',
        'sales.products.search' => 'POS product search',
        'sales.resume' => 'Resume held sale',
        'sales.show' => 'View sale',
        'sales.receipt' => 'View sale receipt',
        'sales.void' => 'Void sale',
        'reports.finance-income' => 'Income report',
        'reports.finance-expenses' => 'Expense report',
        'reports.finance-summary' => 'Finance summary report',
        'finance.income-categories.index' => 'List income categories',
        'finance.income-categories.create' => 'Create income category form',
        'finance.income-categories.store' => 'Store income category',
        'finance.income-categories.edit' => 'Edit income category form',
        'finance.income-categories.update' => 'Update income category',
        'finance.expense-categories.index' => 'List expense categories',
        'finance.expense-categories.create' => 'Create expense category form',
        'finance.expense-categories.store' => 'Store expense category',
        'finance.expense-categories.edit' => 'Edit expense category form',
        'finance.expense-categories.update' => 'Update expense category',
        'product-categories.index' => 'List product categories',
        'product-categories.create' => 'Create product category form',
        'product-categories.store' => 'Store product category',
        'product-categories.edit' => 'Edit product category form',
        'product-categories.update' => 'Update product category',
        'products.index' => 'List products',
        'products.create' => 'Create product form',
        'products.store' => 'Store product',
        'products.show' => 'View product',
        'products.edit' => 'Edit product form',
        'products.update' => 'Update product',
        'suppliers.index' => 'List suppliers',
        'suppliers.create' => 'Create supplier form',
        'suppliers.store' => 'Store supplier',
        'suppliers.edit' => 'Edit supplier form',
        'suppliers.update' => 'Update supplier',
        'opening-stock.create' => 'Opening stock form',
        'opening-stock.store' => 'Store opening stock',
        'purchase-receipts.index' => 'List purchase receipts',
        'purchase-receipts.create' => 'Create purchase receipt form',
        'purchase-receipts.store' => 'Store purchase receipt',
        'purchase-receipts.show' => 'View purchase receipt',
        'purchase-receipts.post' => 'Post purchase receipt',
        'stock.index' => 'Stock index',
        'stock.ledger' => 'Stock ledger',
        'stock-control.low-stock' => 'Low-stock alerts',
        'stock-control.expiry' => 'Expiry alerts',
        'stock-adjustments.create' => 'Stock adjustment form',
        'stock-adjustments.store' => 'Store stock adjustment',
        'stock-counts.index' => 'List stock counts',
        'stock-counts.create' => 'Create stock count form',
        'stock-counts.store' => 'Store stock count',
        'stock-counts.show' => 'View stock count',
        'stock-counts.update' => 'Update stock count',
        'stock-counts.submit' => 'Submit stock count',
        'stock-counts.post' => 'Post stock count',
        'stock-counts.cancel' => 'Cancel stock count',
        'reports.stock-on-hand' => 'Stock on hand report',
        'reports.stock-movements' => 'Stock movements report',
        'reports.low-stock' => 'Low-stock report',
        'reports.expiry' => 'Expiry report',
        'reports.stock-adjustments' => 'Stock adjustments report',
        'admin.users.index' => 'List users',
        'admin.users.create' => 'Create user form',
        'admin.users.store' => 'Store user',
        'admin.users.edit' => 'Edit user form',
        'admin.users.update' => 'Update user',
        'admin.users.reset-password' => 'Reset user password',
        'admin.roles.index' => 'List roles',
        'admin.roles.edit' => 'Edit role permissions form',
        'admin.roles.update' => 'Update role permissions',
        'product-categories.destroy' => 'Delete product category',
        'products.destroy' => 'Delete product',
        'suppliers.destroy' => 'Delete supplier',
        'finance.income-categories.destroy' => 'Delete income category',
        'finance.expense-categories.destroy' => 'Delete expense category',
        'admin.users.destroy' => 'Delete user',
        'backup-restore.index' => 'Backup and restore screen',
        'backup-restore.export.csv' => 'Export dataset CSV',
        'backup-restore.export.sql' => 'Export dataset SQL',
        'backup-restore.import' => 'Import dataset CSV or XLSX',
        'backup-restore.restore.sql' => 'Restore dataset SQL',
        'backup-restore.database.export' => 'Export full database SQL',
        'backup-restore.database.restore' => 'Restore full database SQL',
    ],

    /*
    |--------------------------------------------------------------------------
    | Screen Permissions
    |--------------------------------------------------------------------------
    | Keys are screen keys used in navigation. Permission slugs are screen.{key}.
    */
    'screens' => [
        'dashboard' => 'Dashboard',
        'sales.pos' => 'POS',
        'patients' => 'Patients',
        'sales.index' => 'Sales History',
        'products' => 'Products',
        'product-categories' => 'Product Categories',
        'suppliers' => 'Suppliers',
        'opening-stock' => 'Opening Stock',
        'purchase-receipts' => 'Purchase Receipts',
        'stock' => 'Stock Ledger',
        'stock-control.low-stock' => 'Low-Stock Alerts',
        'stock-control.expiry' => 'Expiry Alerts',
        'stock-counts' => 'Stock Counts',
        'finance.income-categories' => 'Income Categories',
        'finance.expense-categories' => 'Expense Categories',
        'finance.income' => 'Income',
        'finance.expenses' => 'Expenses',
        'reports.finance-summary' => 'Finance Summary',
        'reports.finance-income' => 'Income Report',
        'reports.finance-expenses' => 'Expense Report',
        'reports.stock' => 'Stock Reports',
        'admin.users' => 'Users',
        'admin.roles' => 'Roles & Permissions',
        'backup-restore' => 'Backup & Restore',
    ],

    /*
    |--------------------------------------------------------------------------
    | Default Role Grants
    |--------------------------------------------------------------------------
    | Mirrors pre-Phase-6 middleware groups. Admin uses wildcard.
    */
    'role_grants' => [
        'admin' => ['*'],
        'cashier' => [
            'routes' => [
                'dashboard',
                'logout',
                'sales.patient-visits.today-recent',
                'patient-visits.show',
                'patient-visits.diagnoses.store',
                'patient-visits.diagnoses.edit',
                'patient-visits.diagnoses.update',
                'patients.index',
                'patients.create',
                'patients.store',
                'patients.show',
                'patients.edit',
                'patients.update',
                'patients.visit-records.create',
                'patients.visit-records.store',
                'patients.visit-records.edit',
                'patients.visit-records.update',
                'finance.income.index',
                'finance.income.create',
                'finance.income.store',
                'finance.income.edit',
                'finance.income.update',
                'finance.expenses.index',
                'finance.expenses.create',
                'finance.expenses.store',
                'finance.expenses.edit',
                'finance.expenses.update',
                'sales.index',
                'sales.pos',
                'sales.hold',
                'sales.store',
                'sales.products.search',
                'sales.resume',
                'sales.show',
                'sales.receipt',
                'reports.finance-income',
                'reports.finance-expenses',
            ],
            'screens' => [
                'dashboard',
                'sales.pos',
                'patients',
                'sales.index',
                'finance.income',
                'finance.expenses',
                'reports.finance-income',
                'reports.finance-expenses',
            ],
        ],
        'pharmacist' => [
            'inherits' => 'cashier',
            'routes' => [
                'sales.void',
                'reports.finance-summary',
                'finance.income-categories.index',
                'finance.income-categories.create',
                'finance.income-categories.store',
                'finance.income-categories.edit',
                'finance.income-categories.update',
                'finance.income-categories.destroy',
                'finance.expense-categories.index',
                'finance.expense-categories.create',
                'finance.expense-categories.store',
                'finance.expense-categories.edit',
                'finance.expense-categories.update',
                'finance.expense-categories.destroy',
                'product-categories.index',
                'product-categories.create',
                'product-categories.store',
                'product-categories.edit',
                'product-categories.update',
                'product-categories.destroy',
                'products.index',
                'products.create',
                'products.store',
                'products.show',
                'products.edit',
                'products.update',
                'products.destroy',
                'suppliers.index',
                'suppliers.create',
                'suppliers.store',
                'suppliers.edit',
                'suppliers.update',
                'suppliers.destroy',
                'opening-stock.create',
                'opening-stock.store',
                'purchase-receipts.index',
                'purchase-receipts.create',
                'purchase-receipts.store',
                'purchase-receipts.show',
                'purchase-receipts.post',
                'stock.index',
                'stock.ledger',
                'stock-control.low-stock',
                'stock-control.expiry',
                'stock-adjustments.create',
                'stock-adjustments.store',
                'stock-counts.index',
                'stock-counts.create',
                'stock-counts.store',
                'stock-counts.show',
                'stock-counts.update',
                'stock-counts.submit',
                'stock-counts.post',
                'stock-counts.cancel',
                'reports.stock-on-hand',
                'reports.stock-movements',
                'reports.low-stock',
                'reports.expiry',
                'reports.stock-adjustments',
            ],
            'screens' => [
                'reports.finance-summary',
                'finance.income-categories',
                'finance.expense-categories',
                'products',
                'product-categories',
                'suppliers',
                'opening-stock',
                'purchase-receipts',
                'stock',
                'stock-control.low-stock',
                'stock-control.expiry',
                'stock-counts',
                'reports.stock',
            ],
        ],
        'stock_manager' => [
            'routes' => [
                'dashboard',
                'logout',
                'product-categories.index',
                'product-categories.create',
                'product-categories.store',
                'product-categories.edit',
                'product-categories.update',
                'products.index',
                'products.create',
                'products.store',
                'products.show',
                'products.edit',
                'products.update',
                'suppliers.index',
                'suppliers.create',
                'suppliers.store',
                'suppliers.edit',
                'suppliers.update',
                'opening-stock.create',
                'opening-stock.store',
                'purchase-receipts.index',
                'purchase-receipts.create',
                'purchase-receipts.store',
                'purchase-receipts.show',
                'purchase-receipts.post',
                'stock.index',
                'stock.ledger',
                'stock-control.low-stock',
                'stock-control.expiry',
                'stock-adjustments.create',
                'stock-adjustments.store',
                'stock-counts.index',
                'stock-counts.create',
                'stock-counts.store',
                'stock-counts.show',
                'stock-counts.update',
                'stock-counts.submit',
                'stock-counts.post',
                'stock-counts.cancel',
                'reports.stock-on-hand',
                'reports.stock-movements',
                'reports.low-stock',
                'reports.expiry',
                'reports.stock-adjustments',
            ],
            'screens' => [
                'dashboard',
                'products',
                'product-categories',
                'suppliers',
                'opening-stock',
                'purchase-receipts',
                'stock',
                'stock-control.low-stock',
                'stock-control.expiry',
                'stock-counts',
                'reports.stock',
            ],
        ],
    ],
];
